// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cciticaeoendqfokjrgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjaXRpY2Flb2VuZHFmb2tqcmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTc4OTIsImV4cCI6MjA2MzA3Mzg5Mn0.c3voBLed_9XaJLUtslpgViL_fd3zXqm_paNJ7Ne9V8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);